import type { MenuItem } from "./types"

export const menuItems: MenuItem[] = [
  // Coffee
  {
    id: "coffee-1",
    name: "Espresso",
    description: "Our signature espresso blend with notes of chocolate and caramel",
    price: 120,
    category: "Coffee",
    image: "/espresso-in-cup.png",
  },
  {
    id: "coffee-2",
    name: "Cappuccino",
    description: "Espresso with steamed milk and a thick layer of foam",
    price: 160,
    category: "Coffee",
    image: "/cappuccino-coffee.png",
  },
  {
    id: "coffee-3",
    name: "Latte",
    description: "Espresso with steamed milk and a light layer of foam",
    price: 180,
    category: "Coffee",
    image: "/latte-coffee.png",
  },
  {
    id: "coffee-4",
    name: "Americano",
    description: "Espresso diluted with hot water",
    price: 140,
    category: "Coffee",
    image: "/americano-coffee.png",
  },
  {
    id: "coffee-5",
    name: "Flat White",
    description: "Espresso with steamed milk and minimal foam",
    price: 180,
    category: "Coffee",
    image: "/flat-white.png",
  },
  {
    id: "coffee-6",
    name: "Mocha",
    description: "Espresso with chocolate and steamed milk",
    price: 195,
    category: "Coffee",
    image: "/mocha-coffee.png",
  },

  // Pastries
  {
    id: "pastry-1",
    name: "Butter Croissant",
    description: "Classic French croissant made with premium butter",
    price: 85,
    category: "Pastries",
    image: "/placeholder.svg?height=300&width=400&query=butter croissant",
  },
  {
    id: "pastry-2",
    name: "Pain au Chocolat",
    description: "Buttery pastry filled with dark chocolate",
    price: 95,
    category: "Pastries",
    image: "/placeholder.svg?height=300&width=400&query=pain au chocolat",
  },
  {
    id: "pastry-3",
    name: "Almond Croissant",
    description: "Croissant filled with almond cream and topped with sliced almonds",
    price: 110,
    category: "Pastries",
    image: "/placeholder.svg?height=300&width=400&query=almond croissant",
  },
  {
    id: "pastry-4",
    name: "Belgian Waffle",
    description: "Traditional Belgian waffle with pearl sugar",
    price: 150,
    category: "Pastries",
    image: "/placeholder.svg?height=300&width=400&query=belgian waffle",
  },
  {
    id: "pastry-5",
    name: "Cinnamon Roll",
    description: "Soft roll with cinnamon filling and cream cheese frosting",
    price: 130,
    category: "Pastries",
    image: "/placeholder.svg?height=300&width=400&query=cinnamon roll",
  },
  {
    id: "pastry-6",
    name: "Apple Turnover",
    description: "Flaky pastry filled with caramelized apples and cinnamon",
    price: 120,
    category: "Pastries",
    image: "/placeholder.svg?height=300&width=400&query=apple turnover",
  },

  // Combos
  {
    id: "combo-1",
    name: "Cyclist's Combo",
    description: "Espresso and butter croissant - perfect for a quick energy boost",
    price: 190,
    category: "Combos",
    image: "/placeholder.svg?height=300&width=400&query=coffee and croissant",
  },
  {
    id: "combo-2",
    name: "Morning Starter",
    description: "Cappuccino and pain au chocolat to start your day right",
    price: 240,
    category: "Combos",
    image: "/placeholder.svg?height=300&width=400&query=cappuccino and chocolate pastry",
  },
  {
    id: "combo-3",
    name: "Afternoon Delight",
    description: "Latte and almond croissant for a perfect afternoon break",
    price: 270,
    category: "Combos",
    image: "/placeholder.svg?height=300&width=400&query=latte and almond pastry",
  },
  {
    id: "combo-4",
    name: "Belgian Special",
    description: "Flat white and Belgian waffle with a side of chocolate sauce",
    price: 310,
    category: "Combos",
    image: "/placeholder.svg?height=300&width=400&query=coffee and belgian waffle",
  },
  {
    id: "combo-5",
    name: "Sweet Tooth",
    description: "Mocha and cinnamon roll - a sweet treat for any time of day",
    price: 300,
    category: "Combos",
    image: "/placeholder.svg?height=300&width=400&query=mocha and cinnamon roll",
  },
  {
    id: "combo-6",
    name: "Fruit Lover",
    description: "Americano and apple turnover - a balanced combination",
    price: 240,
    category: "Combos",
    image: "/placeholder.svg?height=300&width=400&query=coffee and apple pastry",
  },
]
